### PR TITLE
Website Makeover

### PR DESCRIPTION
**Pull request by PartialDevAdmin**
A total redesign of the website, using the Bootstrap 4 framework.

### CODE REVIEW

**Comment by PartialDevAdmin** [comment]
@TristianK3604 How is it looking so far?

**Comment by TristianK3604** [comment]
@PartialDevAdmin I am laughing so hard right now! How are we always thinking the same thing at the same time... Anyways, I was going to ask you today about redesigning the website with Bootstrap 4 and a material design look :laughing:! Anyway, I love how you thought the website needed a redesign too, and ill take care of the CSS files (I know where some Material Design Bootstrap 4 is) and customization, let me know if there's anything else.

**Comment by TristianK3604** [comment]
I think we should switch the site over to Jekyll, I like it better since its more blog aware and has an Algolia plugin (super duper fast typo proof search :smile:)!

**Comment by PartialDevAdmin** [comment]
@TristianK3604 Sounds good! I won't be at the office till about 4 your time, and once I am there, I could get Jekyll installed. Sound ok to you?

**Comment by PartialDevAdmin** [comment]
Closed for right now, as the new Jekyll branch may take over this

**Pull request closed without merging**
